parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: edusoho
    database_user: root
    database_password: 'Sy1002427!'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: zh_CN
    secret: j8ulfdjb71cko0kos40og8k4g4og44s
    user_partner: none